# Generated by Django 3.2.6 on 2021-08-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210824_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='details',
            field=models.JSONField(default=dict, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='item',
            name='buying_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sale',
            name='details',
            field=models.JSONField(default=dict, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sale',
            name='loss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shop',
            name='details',
            field=models.JSONField(default=dict, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.JSONField(default=dict, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
