# Generated by Django 3.2.6 on 2021-08-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bussiness_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='details',
            field=models.JSONField(default=dict, verbose_name='details'),
        ),
    ]
